---
- name: Install git on nodes
  hosts: all  
  become: yes

  tasks:
    - name: Install Git
      package:
        name: git
        state: present
        
  tasks:
    - name: Print message
      debug:
        msg: Git Installed Successfully now we will install docker on ansible nodes
  
  tasks:
    - name: install docker 
      package: 
        name: docker
        state: present

  tasks:
    - name: Print message
      debug:
        msg: Docker installed successfully!!! 
